Added onering-deploy script

diff --git a/bin/onering-deploy b/bin/onering-deploy
--- a/bin/onering-deploy
+++ b/bin/onering-deploy
@@ -8,7 +8,10 @@ RELEASE=$(date -u +%Y%m%d%H%M%S)
 
 for i in git openssl ruby rake; do
   which $i > /dev/null 2>&1
-  [ $? -gt 0 ] && (echo "Command not found: $i, cannot continue" && exit 1)
+  if [ $? -gt 0 ]; then
+    echo "Command not found: $i, cannot continue"
+    exit 1
+  fi
 done
 
 # create default everything
